#!/usr/bin/env node
// Writes typed ABIs (`as const`) to src/abi/ from forge build artifacts (contracts/out). The ABI is the compiler's
// output for the contract at HEAD: nothing is hand-written. Re-run after any contract change:
//   (cd contracts && forge build) && node web/scripts/export-abis.mjs
// `--check` re-generates in memory and fails if src/abi/ differs (used by CI / the fresh-clone check).
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(here, "../../contracts/out");
const dest = path.resolve(here, "../src/abi");
const check = process.argv.includes("--check");

// [source file, contract name, export name, kind]
const TARGETS = [
  ["SundownMarket.sol", "SundownMarket", "sundownMarketAbi", "production"],
  ["SundownMarketFactory.sol", "SundownMarketFactory", "sundownMarketFactoryAbi", "production"],
  ["SundownGuard.sol", "SundownGuard", "sundownGuardAbi", "production"],
  ["FlatGuard.sol", "FlatGuard", "flatGuardAbi", "production"],
  ["ChainlinkEquityOracle.sol", "ChainlinkEquityOracle", "chainlinkEquityOracleAbi", "production"],
  ["WindowCache.sol", "WindowCache", "windowCacheAbi", "production"],
  ["MarketCalendar.sol", "MarketCalendar", "marketCalendarAbi", "production"],
  ["SimEquityFeed.sol", "SimEquityFeed", "simEquityFeedAbi", "simulation"],
  ["SimTokens.sol", "SimStock", "simStockAbi", "simulation"],
  ["SimTokens.sol", "SimUSDG", "simUsdgAbi", "simulation"],
  ["SimTokens.sol", "SimIssuerRegistry", "simIssuerRegistryAbi", "simulation"],
];

const files = {};
for (const [src, name, exp, kind] of TARGETS) {
  const p = path.join(out, src, `${name}.json`);
  if (!existsSync(p)) throw new Error(`missing forge artifact ${p}: run \`forge build\` in contracts/ first`);
  const abi = JSON.parse(readFileSync(p, "utf8")).abi;
  const header =
    `// Generated by web/scripts/export-abis.mjs from forge output (contracts/out/${src}/${name}.json). Do not edit.\n` +
    `// ${kind === "simulation" ? "SIMULATION fixture (test token / price feed), not a production contract." : "Production contract."}\n`;
  files[`${exp}.ts`] = `${header}export const ${exp} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
files["index.ts"] =
  "// Generated by web/scripts/export-abis.mjs. Do not edit.\n" +
  TARGETS.map(([, , exp]) => `export { ${exp} } from "./${exp}";`).join("\n") +
  "\n";

if (check) {
  let bad = 0;
  for (const [f, body] of Object.entries(files)) {
    const p = path.join(dest, f);
    if (!existsSync(p) || readFileSync(p, "utf8") !== body) {
      console.error(`stale: src/abi/${f}`);
      bad++;
    }
  }
  if (bad) process.exit(1);
  console.log(`ABIs match forge output (${Object.keys(files).length} files)`);
} else {
  mkdirSync(dest, { recursive: true });
  for (const [f, body] of Object.entries(files)) writeFileSync(path.join(dest, f), body);
  console.log(`wrote ${Object.keys(files).length} ABI files to src/abi/`);
}
