// Generated by web/scripts/export-abis.mjs from forge output (contracts/out/ChainlinkEquityOracle.sol/ChainlinkEquityOracle.json). Do not edit.
// Production contract.
export const chainlinkEquityOracleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct ChainlinkEquityOracle.Config",
        "components": [
          {
            "name": "feed",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "collateralToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "windowCache",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sequencerFeed",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sequencerGrace",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxAge",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "freeAge",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "corporateActionHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deviationWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "ageHaircutWadPerHour",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxAgeHaircutWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minPriceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxPriceWad",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "AGE_HAIRCUT_WAD_PER_HOUR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "COLLATERAL_TOKEN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "CORPORATE_ACTION_HORIZON",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DECIMAL_SCALE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DEVIATION_WAD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FEED",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAggregatorV3"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FREE_AGE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_AGE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_AGE_HAIRCUT_WAD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_PRICE_WAD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_PRICE_WAD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SEQUENCER_FEED",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAggregatorV3"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SEQUENCER_GRACE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "WINDOW_CACHE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IWindowCache"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "peek",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PriceData",
        "components": [
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "haircutWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PriceStatus"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "price",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PriceData",
        "components": [
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "haircutWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PriceStatus"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "error",
    "name": "InvalidConfig",
    "inputs": [
      {
        "name": "field",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  }
] as const;
