// Generated by web/scripts/export-abis.mjs from forge output (contracts/out/SundownMarketFactory.sol/SundownMarketFactory.json). Do not edit.
// Production contract.
export const sundownMarketFactoryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "IMPLEMENTATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createMarket",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct MarketParams",
        "components": [
          {
            "name": "collateralToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "loanToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "oracle",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "guard",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "guardian",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "governance",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "lltvWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "closeFactorWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "criticalHealthWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxBonusWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "collateralCap",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "minDebt",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "baseAprWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "slope1AprWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "slope2AprWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kinkWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "shareName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "shareSymbol",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "market",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isMarket",
    "inputs": [
      {
        "name": "market",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "marketAt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "marketCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictMarket",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct MarketParams",
        "components": [
          {
            "name": "collateralToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "loanToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "oracle",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "guard",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "guardian",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "governance",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "lltvWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "closeFactorWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "criticalHealthWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxBonusWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "collateralCap",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "minDebt",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "baseAprWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "slope1AprWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "slope2AprWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kinkWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "shareName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "shareSymbol",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "MarketCreated",
    "inputs": [
      {
        "name": "market",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "paramsHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "collateralToken",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "loanToken",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "guard",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "oracle",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FailedDeployment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
