// Generated by web/scripts/export-abis.mjs from forge output (contracts/out/SundownGuard.sol/SundownGuard.json). Do not edit.
// Production contract.
export const sundownGuardAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "initial",
        "type": "tuple",
        "internalType": "struct SundownGuard.Params",
        "components": [
          {
            "name": "standardLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "boostedLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapShort",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapWeekend",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapLong",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "oracleBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "safetyBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "bonus",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageFee",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageMargin",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "preWindowHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "cureWindow",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "oracle_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "windows_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "guardian_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "admin_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "timelockDelay",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "collateralDecimals_",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "loanDecimals_",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "GOVERNANCE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "GUARDIAN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_BONUS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_BOOSTED_LLTV",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DELEVERAGE_MARGIN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_GAP_VAR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_HORIZON",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_ORACLE_BUFFER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_SAFETY_BUFFER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_STANDARD_LLTV",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_TIMELOCK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_BONUS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_DELEVERAGE_FEE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_DELEVERAGE_INTERVAL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_HORIZON",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_ORACLE_BUFFER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_STANDARD_LLTV",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_TIMELOCK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ORACLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IEquityOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TIMELOCK_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "WINDOWS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IWindowCache"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bindMarket",
    "inputs": [
      {
        "name": "market_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "blockBorrows",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "boosted",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "boostedEntryDisabled",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "borrowsBlocked",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancelParams",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "clearGuardianFlags",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "currentParams",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct SundownGuard.Params",
        "components": [
          {
            "name": "standardLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "boostedLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapShort",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapWeekend",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapLong",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "oracleBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "safetyBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "bonus",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageFee",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageMargin",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "preWindowHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "cureWindow",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "disableBoostedEntry",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "enterBoosted",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "executeParams",
    "inputs": [
      {
        "name": "next",
        "type": "tuple",
        "internalType": "struct SundownGuard.Params",
        "components": [
          {
            "name": "standardLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "boostedLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapShort",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapWeekend",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapLong",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "oracleBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "safetyBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "bonus",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageFee",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageMargin",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "preWindowHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "cureWindow",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "exitBoosted",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "flag",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "flaggedWindow",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liquidationAllowed",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct AccountCtx",
        "components": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "collateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "haircutWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PriceStatus"
          },
          {
            "name": "lltvWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalBorrowAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liquidationBonus",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct AccountCtx",
        "components": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "collateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "haircutWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PriceStatus"
          },
          {
            "name": "lltvWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalBorrowAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "market",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract SundownMarket"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxBorrowable",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct AccountCtx",
        "components": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "collateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "haircutWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PriceStatus"
          },
          {
            "name": "lltvWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalBorrowAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onBorrow",
    "inputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AccountCtx",
        "components": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "collateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "haircutWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PriceStatus"
          },
          {
            "name": "lltvWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalBorrowAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onLiquidate",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct AccountCtx",
        "components": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "collateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "haircutWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PriceStatus"
          },
          {
            "name": "lltvWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalBorrowAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "liquidator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "repaid",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seized",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "params",
    "inputs": [],
    "outputs": [
      {
        "name": "standardLltv",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "boostedLltv",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "gapShort",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "gapWeekend",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "gapLong",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "oracleBuffer",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "safetyBuffer",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "bonus",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "deleverageFee",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "deleverageMargin",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "preWindowHorizon",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "cureWindow",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "queueParams",
    "inputs": [
      {
        "name": "next",
        "type": "tuple",
        "internalType": "struct SundownGuard.Params",
        "components": [
          {
            "name": "standardLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "boostedLltv",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapShort",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapWeekend",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapLong",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "oracleBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "safetyBuffer",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "bonus",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageFee",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deleverageMargin",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "preWindowHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "cureWindow",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "queuedEta",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "queuedHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteDeleverage",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "eligible",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "debt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "stressCap",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "requiredRepay",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expectedSeized",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "stressFraction",
    "inputs": [
      {
        "name": "cls",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "BoostedEntered",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BoostedEntryDisabledSet",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BoostedExited",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BorrowsBlockedSet",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Deleveraged",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "liquidator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "repaid",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "seized",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "debtBefore",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "stressCap",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "requiredRepay",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Flagged",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "debt",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "stressCap",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GuardianFlagsCleared",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarketBound",
    "inputs": [
      {
        "name": "market",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ParamsCancelled",
    "inputs": [
      {
        "name": "hash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ParamsExecuted",
    "inputs": [
      {
        "name": "hash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ParamsQueued",
    "inputs": [
      {
        "name": "hash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "eta",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyBoosted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyBound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyFlagged",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BindingMismatch",
    "inputs": [
      {
        "name": "field",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "BoostedEntryDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BoostedUnavailable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BorrowsBlocked",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DoesNotFitStandard",
    "inputs": [
      {
        "name": "debt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "EntryNotAllowed",
    "inputs": [
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "HashMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidParam",
    "inputs": [
      {
        "name": "field",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAboveStressCap",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBoosted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotMarket",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingQueued",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PriceUnusable",
    "inputs": [
      {
        "name": "status",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "RepayExceedsRequired",
    "inputs": [
      {
        "name": "repaid",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "requiredRepay",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": [
      {
        "name": "eta",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  }
] as const;
