// Generated by web/scripts/export-abis.mjs from forge output (contracts/out/WindowCache.sol/WindowCache.json). Do not edit.
// Production contract.
export const windowCacheAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "calendar",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CALENDAR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICalendar"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TTL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "peek",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct WindowState",
        "components": [
          {
            "name": "blind",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "start",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "end",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "cls",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "state",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct WindowState",
        "components": [
          {
            "name": "blind",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "windowId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "start",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "end",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "cls",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Refreshed",
    "inputs": [
      {
        "name": "windowId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "start",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "end",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "lastEnd",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintDowncast",
    "inputs": [
      {
        "name": "bits",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
